apiVersion: v1
kind: Service
metadata:
  labels:
    app: ethereum
    chart: ethereum-1.0.2
    component: bootnode
    heritage: Helm
    release: ethereum-test
  name: ethereum-test-bootnode
spec:
  clusterIP: None
  ports:
    - name: discovery
      port: 30301
      protocol: UDP
    - name: http
      port: 80
  selector:
    app: ethereum
    component: bootnode
    release: ethereum-test
