apiVersion: v1
kind: Service
metadata:
  labels:
    app: ethereum
    chart: ethereum-1.0.2
    component: geth-tx
    heritage: Helm
    release: ethereum-test
  name: ethereum-test-geth-tx
spec:
  ports:
    - name: rpc
      port: 8545
    - name: ws
      port: 8546
  selector:
    app: ethereum
    component: geth-tx
    release: ethereum-test
  sessionAffinity: ClientIP
  type: ClusterIP
